// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ICombatSystem {
  function mud_CombatSystem_attack(bytes32 item, int32 targetX, int32 targetY) external;

  function mud_CombatSystem_heal() external;
}
