// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ISpawnerSystem {
  function mud_SpawnerSystem_create(int32 roomX, int32 roomY, int32 x, int32 y) external;

  function mud_SpawnerSystem_spawn(bytes32 spawnerId, int32 x, int32 y) external;
}
