// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

enum AttributeTypes {
  None,
  Fortitude,
  Strong,
  Lightweight,
  Alacrity,
  Swift,
  Godlike
}

enum ItemTypes {
  None,
  Sword,
  Dagger,
  Spear,
  Hammer,
  Axe,
  Shield,
  Bow,
  BowLarge,
  Staff,
  DevilHorn,
  DevilHornLarge
}

enum MonsterTypes {
  None,
  Spawner,
  Skeleton,
  SkeletonArcher,
  Spider
}
