// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Player, PlayerTableId } from "./tables/Player.sol";
import { Room, RoomData, RoomTableId } from "./tables/Room.sol";
import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { MoveSpeed, MoveSpeedTableId } from "./tables/MoveSpeed.sol";
import { Stamina, StaminaData, StaminaTableId } from "./tables/Stamina.sol";
import { ItemType, ItemTypeTableId } from "./tables/ItemType.sol";
import { Attack, AttackData, AttackTableId } from "./tables/Attack.sol";
import { Inventory, InventoryData, InventoryTableId } from "./tables/Inventory.sol";
import { EquippedBy, EquippedByTableId } from "./tables/EquippedBy.sol";
import { InInventoryOf, InInventoryOfTableId } from "./tables/InInventoryOf.sol";
import { Attribute, AttributeData, AttributeTableId } from "./tables/Attribute.sol";
import { OnItem, OnItemTableId } from "./tables/OnItem.sol";
import { BonusAttributes, BonusAttributesData, BonusAttributesTableId } from "./tables/BonusAttributes.sol";
import { MonsterType, MonsterTypeTableId } from "./tables/MonsterType.sol";
import { Spawner, SpawnerTableId } from "./tables/Spawner.sol";
import { Nonce, NonceTableId } from "./tables/Nonce.sol";
import { RngCommit, RngCommitTableId } from "./tables/RngCommit.sol";
