// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum AttributeTypes {
  None,
  Fortitude,
  Strong,
  Lightweight,
  Alacrity,
  Swift,
  Enchanted,
  Sentinel,
  Heavy,
  Featherweight,
  Stiff,
  Untouchable,
  Sustainable,
  Wellmade,
  Long,
  Short,
  Spiked,
  Sharp,
  Mythril,
  Battle,
  Dualwield
}

enum ItemTypes {
  None,
  Sword,
  Dagger,
  Spear,
  Hammer,
  Axe,
  Shield,
  Bow,
  BowLarge,
  Staff,
  DevilHorn,
  DevilHornLarge
}

enum MonsterTypes {
  None,
  Spawner,
  Skeleton,
  SkeletonArcher,
  Spider
}
