// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IInventorySystem {
  function mud_InventorySystem_unequip(bytes32 item) external;
}
