// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMoveSystem {
  function mud_MoveSystem_move(int32[] memory xPath, int32[] memory yPath) external;

  function mud_MoveSystem_moveRoom(int32 x, int32 y) external;
}
