// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { ICombatSystem } from "./ICombatSystem.sol";
import { IInventorySystem } from "./IInventorySystem.sol";
import { IItemSystem } from "./IItemSystem.sol";
import { IMonsterSystem } from "./IMonsterSystem.sol";
import { IMoveSystem } from "./IMoveSystem.sol";
import { IPlayerSystem } from "./IPlayerSystem.sol";
import { ISpawnerSystem } from "./ISpawnerSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is
  IBaseWorld,
  ICombatSystem,
  IInventorySystem,
  IItemSystem,
  IMonsterSystem,
  IMoveSystem,
  IPlayerSystem,
  ISpawnerSystem
{

}
